# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [3]:
!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
print(np.__version__)

2.2.4


In [5]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[10,20],[30,40]],[[1,2],[3,4]],[[1,2],[3,4]]]

In [6]:
n1 = np.array(l1,dtype='f8')
n2 = np.array(l2,dtype='i1')#1 2 4 8
n3 = np.array(l3)

In [7]:
n2.dtype

dtype('int8')

In [8]:
n2.shape

(3, 2)

In [9]:
n3.shape

(3, 2, 2)

In [10]:
print(l1[2],n1[2])

3 3.0


In [11]:
# print(l2[1][1], n2[1][1])
print(l2[1][1], n2[1,1])

4 4


In [12]:
print(l3[0][1][0],n3[0,1,0])

30 30


In [13]:
l2[1]

[3, 4]

In [14]:
n2[1]

array([3, 4], dtype=int8)

In [15]:
n2[1,2,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

more creation methods: arange, linspace, ones, zeros, eye, diag

In [16]:
narr = np.arange(1,11)

In [17]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
np.ones(shape = (5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.zeros(shape=(5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [22]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
narr = np.arange(1,101)

In [24]:
narr = narr.reshape((10,10))

In [25]:
narr.shape

(10, 10)

In [26]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

random numbers: Numpy Random Module
- rand: Random values in given shape
- randn: Return samples from the Standard normal distribution
- randint: Return random integer from low(inclusive) to high(exclusive)
- random: Return random floats in [0.0,1.0)
- choice: Generates a random sample from given 1D array
- Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()

In [27]:
np.random.rand(3,2,2)

array([[[0.44743793, 0.13202534],
        [0.5549649 , 0.94354017]],

       [[0.44876383, 0.11220265],
        [0.13273688, 0.54247703]],

       [[0.90754627, 0.62136115],
        [0.0337768 , 0.04369839]]])

In [28]:
np.random.randn(3,2,2)

array([[[-0.33270053,  1.06851018],
        [ 1.43791909,  1.22350879]],

       [[ 0.11974231, -1.41940127],
        [-1.7462596 ,  0.95819194]],

       [[-1.49915262, -0.40121185],
        [-1.5598713 , -0.58106835]]])

In [29]:
np.random.randint(1,101,size=(5,2))

array([[44, 92],
       [68, 60],
       [41, 62],
       [42, 18],
       [52, 94]], dtype=int32)

In [30]:
np.random.random(size=(5,2))

array([[0.91611781, 0.17028128],
       [0.07873463, 0.36324784],
       [0.44541739, 0.48803725],
       [0.1140951 , 0.59261062],
       [0.02800026, 0.19529321]])

In [31]:
np.random.choice(np.array([1,2,3,4,5,6,7,8,9]),size=(5,),replace = True,p = [0,0,0,0,0.3,0.3,0.1,0.3,0])

array([7, 6, 6, 6, 7])

In [32]:
narr = np.arange(1,101).reshape((10,10))
np.random.shuffle(narr)

In [33]:
narr

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]])

In [34]:
narr = np.arange(1,101)

In [35]:
narr = narr.reshape((5,2,-1))

In [36]:
narr

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [37]:
narr.reshape((-1,))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [38]:
narr[1,1,4] = 350

In [39]:
narr

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34, 350,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [40]:
narr = narr.reshape((5,2,-1))

In [41]:
narr[1,1,4] = 350

In [42]:
narr[1:4,:,2:6]

array([[[ 23,  24,  25,  26],
        [ 33,  34, 350,  36]],

       [[ 43,  44,  45,  46],
        [ 53,  54,  55,  56]],

       [[ 63,  64,  65,  66],
        [ 73,  74,  75,  76]]])

In [43]:
narr = np.arange(1,101).reshape((10,10))

In [44]:
narr[3:7,4:8] = np.eye(4)

In [45]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [46]:
brr = narr[3:7,4:8].copy()

In [47]:
brr[1:3,1:3] = np.ones(shape=(2,2))

In [48]:
brr

array([[1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [49]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [50]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([10,20,30,40,50])

In [51]:
n1 > 3

array([False, False, False,  True,  True])

In [52]:
n1+n2

array([11, 22, 33, 44, 55])

In [54]:
n1,n2

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [56]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[1,2,3],[4,5,6]])
n1,n2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [82]:
print(n1[1,[2]]) #fancy indexing

[6]


In [85]:
print(n2[[True,False],[True,False,True]])

[1 3]


## Filtering in ML

In [94]:
nz = np.arange(1,23,2)
nz

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [96]:
nz[nz>5].reshape(4,2)

array([[ 7,  9],
       [11, 13],
       [15, 17],
       [19, 21]])

In [111]:
nh =np.array( [[[1,2],[3,4],[5,6]],[[11,22],[33,44],[55,66]]])
nh
#Learn about axis 




array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[11, 22],
        [33, 44],
        [55, 66]]])

In [112]:
### nditer

In [115]:
for t in np.nditer(nh):
    print(t)
for t in np.ndenumerate(nh):
    #prints index and value
    print(t)

1
2
3
4
5
6
11
22
33
44
55
66
((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 1, 0), np.int64(3))
((0, 1, 1), np.int64(4))
((0, 2, 0), np.int64(5))
((0, 2, 1), np.int64(6))
((1, 0, 0), np.int64(11))
((1, 0, 1), np.int64(22))
((1, 1, 0), np.int64(33))
((1, 1, 1), np.int64(44))
((1, 2, 0), np.int64(55))
((1, 2, 1), np.int64(66))


In [116]:
#TO merge column and rows of any array 

In [121]:
n1=n1[:1]
n1

array([[1, 2, 3]])

In [124]:
n2=n2[:1]
n2

array([[1, 2, 3]])

In [125]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [1, 2, 3]])

In [126]:
np.hstack((n1,n2))

array([[1, 2, 3, 1, 2, 3]])

In [130]:
np.concatenate((n1,n2),axis =0)

array([[1, 2, 3],
       [1, 2, 3]])

In [135]:
np.stack((n1,n2),axis =0)

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [145]:
# np.hsplit(nz)

In [146]:
nq = np.arange(1,13).reshape(4,3)
nq

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [151]:
print(nq+ np.array([1,2,3]))

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [153]:
#Broadcasting took place above and every time we have either 1 row or 1 column
#For broadcasting 1 para should be same and other should be 1
print(nq+ np.array([[10],[10],[10],[10]]))

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [157]:
np.array([[10],[10],[10],[10]])+np.array([1,2,3])
# here this has 4 row but 1 col     this has 1 row 3 col broadcasting for both array to make 4X3

array([[11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13]])

In [163]:
aj =np.loadtxt('ted.txt')


In [179]:
print(aj)
a =np.max(aj[[0,20],[3]])

print(a)
print(np.max(aj[[0,20],[1]]))
print(np.max(aj[[0,20],[2]]))
idx =np.argmax(aj[[0,20],[3]])
print(idx)
# print(aj[])


[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]
48300.0
30000.0
8600.0
0


In [180]:
# to print max val and year corresponding to that 

In [181]:
# to muliply matrix we use dot()
aj.max(axis =0)

array([ 1920., 77400., 59400., 48300.])

In [183]:
aj[:,0][aj.argmax(axis=0)][1:]

array([1903., 1904., 1900.])

In [184]:
# mutiply array using dot product 